// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Job struct {
	ID          int64
	JobType     string
	Payload     []byte
	Status      string
	Heartbeat   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	Attempts    int32
	MaxAttempts int32
	RanBy       pgtype.Text
}
