// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimJob = `-- name: ClaimJob :one
UPDATE jobs
SET status = 'running', ran_by = $1, heartbeat = now()
WHERE id = (
    SELECT id FROM jobs
    WHERE status = 'pending'
    ORDER BY created_at
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, job_type, payload, attempts
`

type ClaimJobRow struct {
	ID       int64
	JobType  string
	Payload  []byte
	Attempts int32
}

func (q *Queries) ClaimJob(ctx context.Context, ranBy pgtype.Text) (ClaimJobRow, error) {
	row := q.db.QueryRow(ctx, claimJob, ranBy)
	var i ClaimJobRow
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.Payload,
		&i.Attempts,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :exec
UPDATE jobs
SET status = 'completed'
WHERE id = $1
`

func (q *Queries) CompleteJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, completeJob, id)
	return err
}

const failJob = `-- name: FailJob :exec
UPDATE jobs
SET status = 'failed', attempts = attempts + 1
WHERE id = $1 AND attempts + 1 >= max_attempts
`

func (q *Queries) FailJob(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, failJob, id)
	return err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO jobs (job_type, payload)
VALUES ($1, $2)
RETURNING id
`

type InsertJobParams struct {
	JobType string
	Payload []byte
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertJob, arg.JobType, arg.Payload)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const reapStaleJobs = `-- name: ReapStaleJobs :exec
UPDATE jobs
SET status = 'pending'
WHERE status = 'running' AND heartbeat < now() - interval '30 seconds'
`

func (q *Queries) ReapStaleJobs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, reapStaleJobs)
	return err
}

const retryJob = `-- name: RetryJob :execrows
UPDATE jobs
SET status = 'pending', attempts = attempts + 1
WHERE id = $1 AND attempts + 1 < max_attempts
`

func (q *Queries) RetryJob(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, retryJob, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateHeartbeat = `-- name: UpdateHeartbeat :exec
UPDATE jobs
SET heartbeat = now()
WHERE id = $1
`

func (q *Queries) UpdateHeartbeat(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateHeartbeat, id)
	return err
}
